name: Shell commands

permissions:
  contents: write
  
on:
  push:
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip pandas

    - name: Fetch data script
      run: python load.py

